// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrKS7L7Wd1FTK42jKkpdLkSqanWRQJmzY',
    appId: '1:540290507183:web:9fa62916287dbac37e4f5a',
    messagingSenderId: '540290507183',
    projectId: 'vize-030119026',
    authDomain: 'vize-030119026.firebaseapp.com',
    storageBucket: 'vize-030119026.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC1eV35QpsgvKw2H9yhvy_hIvvAYbqSDQ',
    appId: '1:540290507183:android:7040a8ac61b908037e4f5a',
    messagingSenderId: '540290507183',
    projectId: 'vize-030119026',
    storageBucket: 'vize-030119026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6TzQlTCx2tEKgL0l3ll1TGUgDWTbXpXE',
    appId: '1:540290507183:ios:014f2fe12dc528c47e4f5a',
    messagingSenderId: '540290507183',
    projectId: 'vize-030119026',
    storageBucket: 'vize-030119026.appspot.com',
    iosClientId: '540290507183-kdukqfst6s11579t1snt4b25pl0ojjkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6TzQlTCx2tEKgL0l3ll1TGUgDWTbXpXE',
    appId: '1:540290507183:ios:014f2fe12dc528c47e4f5a',
    messagingSenderId: '540290507183',
    projectId: 'vize-030119026',
    storageBucket: 'vize-030119026.appspot.com',
    iosClientId: '540290507183-kdukqfst6s11579t1snt4b25pl0ojjkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
